import {
  siAndroid,
  siAngular,
  siAnthropic,
  siApple,
  siAxios,
  siBabel,
  siBootstrap,
  siCapacitor,
  siClaude,
  siCloudflare,
  siCss,
  siDocker,
  siEslint,
  siExpress,
  siFastlane,
  siFirebase,
  siFramer,
  siGit,
  siGithub,
  siGithubactions,
  siGmail,
  siGooglecloud,
  siGooglemaps,
  siGraphql,
  siHtml5,
  siHuggingface,
  siJavascript,
  siJest,
  siKubernetes,
  siLangchain,
  siMacos,
  siMapbox,
  siMaterialdesign,
  siMongodb,
  siMui,
  siMysql,
  siChartdotjs,
  siDatadog,
  siNestjs,
  siNextdotjs,
  siNewrelic,
  siNodedotjs,
  siOpenrouter,
  siPostgresql,
  siPostman,
  siPrisma,
  siPython,
  siPytorch,
  siReact,
  siRedis,
  siRedux,
  siSass,
  siShopify,
  siSocketdotio,
  siStripe,
  siSupabase,
  siSwagger,
  siTailwindcss,
  siTensorflow,
  siTestinglibrary,
  siToptal,
  siTypescript,
  siUdacity,
  siVercel,
  siWebpack,
  siWhatsapp,
  siWorldhealthorganization,
  siYoutube,
} from "simple-icons/icons";
import type { SimpleIcon } from "simple-icons";
import {
  Atom,
  Cloud,
  Code2,
  Network,
  ServerCog,
  Smartphone,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { SkillCategory } from "../data/portfolio";

const linkedInIcon: SimpleIcon = {
  title: "LinkedIn",
  slug: "linkedin",
  hex: "0A66C2",
  source: "https://brand.linkedin.com",
  path: "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z",
  svg: '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>LinkedIn</title><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>',
};

export const skillIcons: Record<SkillCategory["icon"], LucideIcon> = {
  frontend: Code2,
  backend: ServerCog,
  mobile: Smartphone,
  cloud: Cloud,
  ai: Atom,
  architecture: Network,
};

export const brandIcons: Record<string, SimpleIcon> = {
  Toptal: siToptal,
  LinkedIn: linkedInIcon,
  Gmail: siGmail,
  GitHub: siGithub,
  WhatsApp: siWhatsapp,
  React: siReact,
  "React.js": siReact,
  "React Native": siReact,
  "Context API": siReact,
  "Mobile App Development": siReact,
  "Web Development": siReact,
  "Front-end": siReact,
  "Single-page Applications (SPAs)": siReact,
  "Next.js": siNextdotjs,
  TypeScript: siTypescript,
  JavaScript: siJavascript,
  SCSS: siSass,
  "Tailwind CSS": siTailwindcss,
  "Framer Motion": siFramer,
  "Node.js": siNodedotjs,
  "Full-stack": siNodedotjs,
  "Express.js": siExpress,
  NestJS: siNestjs,
  "REST APIs": siPostman,
  APIs: siSwagger,
  "Third-party APIs": siSwagger,
  "Third-party Integration": siPostman,
  GraphQL: siGraphql,
  SQL: siPostgresql,
  PostgreSQL: siPostgresql,
  NoSQL: siMongodb,
  Redis: siRedis,
  Caching: siRedis,
  Supabase: siSupabase,
  "Complex Booking": siSupabase,
  iOS: siApple,
  Android: siAndroid,
  "Apple HealthKit": siApple,
  "Apple fit": siApple,
  Capacitor: siCapacitor,
  Fastlane: siFastlane,
  Vercel: siVercel,
  Startups: siVercel,
  "Enterprise SaaS": siVercel,
  Docker: siDocker,
  "GitHub Actions": siGithubactions,
  "CI/CD Pipelines": siGithubactions,
  Kubernetes: siKubernetes,
  Cloudflare: siCloudflare,
  "Google Cloud": siGooglecloud,
  Claude: siClaude,
  "Claude Code": siClaude,
  Anthropic: siAnthropic,
  "Hugging Face": siHuggingface,
  LangChain: siLangchain,
  TensorFlow: siTensorflow,
  PyTorch: siPytorch,
  OpenRouter: siOpenrouter,
  "Large Language Models (LLMs)": siHuggingface,
  "Artificial Intelligence (AI)": siAnthropic,
  "AI Chatbots": siAnthropic,
  "Prompt Engineering": siAnthropic,
  Vectors: siOpenrouter,
  Prisma: siPrisma,
  "Software Architecture": siPrisma,
  MongoDB: siMongodb,
  Firebase: siFirebase,
  "Firebase Cloud Messaging (FCM)": siFirebase,
  "Cloud Firestore": siFirebase,
  MySQL: siMysql,
  Mapbox: siMapbox,
  "Google Maps": siGooglemaps,
  "Google Maps API": siGooglemaps,
  "Google API": siGooglecloud,
  Redux: siRedux,
  "React Redux": siRedux,
  "Redux Toolkit": siRedux,
  Bootstrap: siBootstrap,
  "React-Bootstrap": siBootstrap,
  HTML: siHtml5,
  HTML5: siHtml5,
  CSS: siCss,
  Angular: siAngular,
  "Material UI": siMui,
  "User Interface (UI)": siMaterialdesign,
  "User Experience (UX)": siMaterialdesign,
  "App UI": siMaterialdesign,
  Jest: siJest,
  "Unit Testing": siTestinglibrary,
  Python: siPython,
  Git: siGit,
  Webpack: siWebpack,
  Babel: siBabel,
  ESLint: siEslint,
  Axios: siAxios,
  Stripe: siStripe,
  Fintech: siStripe,
  "Socket.IO": siSocketdotio,
  Sockets: siSocketdotio,
  WebRTC: siSocketdotio,
  Udacity: siUdacity,
  MacOS: siMacos,
  Charts: siChartdotjs,
  Dashboards: siChartdotjs,
  "Healthcare Services": siWorldhealthorganization,
  "Video Streaming": siYoutube,
  "Over-the-top Content (OTT)": siYoutube,
  "Retail & Wholesale": siShopify,
  "Performance Optimization": siDatadog,
  Optimization: siNewrelic,
  Debugging: siDatadog,
  "Software Development": siGithub,
  Enterprise: siToptal,
};

export type BrandLogoImage = {
  src: string;
  tone: string;
};

const favicon = (domain: string) => `https://www.google.com/s2/favicons?sz=64&domain=${domain}`;

export const brandLogoImages: Record<string, BrandLogoImage> = {
  "AWS Amplify": { src: favicon("aws.amazon.com/amplify"), tone: "#ff9900" },
  "Amazon Cognito": { src: favicon("aws.amazon.com/cognito"), tone: "#ff9900" },
  "AWS AppSync": { src: favicon("aws.amazon.com/appsync"), tone: "#ff9900" },
  "AWS Lambda": { src: favicon("aws.amazon.com/lambda"), tone: "#ff9900" },
  "Amazon Web Services (AWS)": { src: favicon("aws.amazon.com"), tone: "#ff9900" },
  "Amazon EC2": { src: favicon("aws.amazon.com/ec2"), tone: "#ff9900" },
  "Amazon DynamoDB": { src: favicon("aws.amazon.com/dynamodb"), tone: "#ff9900" },
  "Amazon S3 (AWS S3)": { src: favicon("aws.amazon.com/s3"), tone: "#ff9900" },
  Azure: { src: favicon("azure.microsoft.com"), tone: "#0078d4" },
  "Azure Queue Storage": { src: favicon("azure.microsoft.com"), tone: "#0078d4" },
  "Azure Blobs": { src: favicon("azure.microsoft.com"), tone: "#0078d4" },
  "Visual Studio Code (VS Code)": { src: favicon("code.visualstudio.com"), tone: "#007acc" },
  RxJS: { src: favicon("rxjs.dev"), tone: "#b7178c" },
  Karma: { src: favicon("karma-runner.github.io"), tone: "#56c5a8" },
  CometChat: { src: favicon("cometchat.com"), tone: "#6852d6" },
  "Kendo UI": { src: favicon("telerik.com/kendo-ui"), tone: "#5ce500" },
  Pinecone: { src: favicon("pinecone.io"), tone: "#00e0a4" },
  Chargebee: { src: favicon("chargebee.com"), tone: "#6d5dfc" },
  PostGIS: { src: favicon("postgis.net"), tone: "#336791" },
  GeoServer: { src: favicon("geoserver.org"), tone: "#3f7f3f" },
  "Security Software Development": { src: favicon("owasp.org"), tone: "#7b61ff" },
  Agile: { src: favicon("atlassian.com"), tone: "#0052cc" },
  "UX Design": { src: favicon("figma.com"), tone: "#a259ff" },
  "Cross-platform": { src: favicon("reactnative.dev"), tone: "#61dafb" },
  Brownfield: { src: favicon("github.com"), tone: "#f4f4f5" },
};
